### ISSUE TITLE
Hi, what is a Nix Expression Repository?

### ISSUE THREAD

**Issue by jgarte** [thelegy/yaner#1]
Hi, what is a Nix Expression Repository?

**Comment by thelegy** [comment]
Hi, this is a git repository for a bunch of nix expressions. Basically it contains configurations for a couple of my machines, as well as some modules / packages.

Like other people publish their dotfiles as a resource for others I publish my nixos expressions.

Also this repo is a little bit of an incubator for me. A place where I can start to hack on stuff and evaluate. Then later, when I like some content I can move the parts to different repositories, like I previously did with my firewall: https://github.com/thelegy/nixos-nftables-firewall

I hope this is enough of an explanation. If you have any questions feel free to reopen this issue or create a new one.
